# Generated by Django 4.2.11 on 2024-03-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='experpt',
            new_name='excerpt',
        ),
    ]
